services:
  bot:
    build: .
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./discord-translator.json:/app/discord-translator.json:ro
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/discord-translator.json
    restart: unless-stopped
